<?php $options = $this->getSelectOptions();?>
<script type="text/javascript">
//<![CDATA[
OptionTemplate<?php echo $this->getType();?> = '<table class="border" cellpadding="0" cellspacing="0">'+
        '<select name="grid[fields][{{field_id}}][field]">' +
            <?php foreach ($options as $option) { ?>
            '<option value="<?php echo $option['value'];?>"><?php echo $option['label'];?></option>'+
            <?php } ?>
        '</select>'+
        '</table>';

//]]>
</script>
