<div class="grid">

  <table id="answer_grid" class="data" cellspacing="0">
    <thead>
      <tr class="headings">
        <th>Label</th>
        <th>Description</th>
        <th>Image</th>
        <th>Clear Other</th>
        <th>&nbsp;</th>
      </tr>
    </thead>
    <tbody>
    </tbody>
  </table>

</div>
  <p class="a-right">
    <button id="add_answer_btn" type="button" class="button">Add</button>
  </p>
